version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHON_SERVER_URL=http://python-server:8000
    restart: always
    depends_on:
      - python-server

  python-server:
    build: 
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: /
        VITE_PYTHON_BASE: /python
    ports:
      - "3000:80" # Maps port 80 (Nginx) from the container to port 3000 on the host
    restart: unless-stopped
    depends_on:
      - backend
networks:
  default:
    driver: bridge